# Generated by Django 5.0.7 on 2024-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_subject_slug_subject_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='detail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
